const mainColor = {
  white: '#fff',
  black: '#000',
  primaryBlue: '#1C84C1',
  primaryBlack: '#1C1C1C',
  primaryGreen: '#64BB1C',
  darkBlue: '#061A27',
  darkBlack: '#060606',
  darkGreen: '#142506',
  lightBlue: '#D2E6F3',
  lightBlack: '#D2D2D2',
  lightGreen: '#E0F1D2',
  midDarkBlue: '#135881',
  midDarkBlack: '#131313',
  midDarkGreen: '#437D13',
  midLightBlue: '#8EC2E0',
  midLightBlack: '#8E8E8E',
  midLightGreen: '#B2DD8E',
  midDarkRed: '#8C0C0C',
};

export const colors = {
  white: mainColor.white,
  black: mainColor.black,
  primaryBlue: mainColor.primaryBlue,
  primaryBlack: mainColor.primaryBlack,
  primaryGreen: mainColor.primaryGreen,
  darkBlue: mainColor.darkBlue,
  darkBlack: mainColor.darkBlack,
  darkGreen: mainColor.darkGreen,
  lightBlue: mainColor.lightBlue,
  lightBlack: mainColor.lightBlack,
  lightGreen: mainColor.lightGreen,
  midDarkBlue: mainColor.midDarkBlue,
  midDarkBlack: mainColor.midDarkBlack,
  midDarkGreen: mainColor.midDarkGreen,
  midLightBlue: mainColor.midLightBlue,
  midLightBlack: mainColor.midLightBlack,
  midLightGreen: mainColor.midLightGreen,
  midDarkRed: mainColor.midDarkRed,
};
